# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackid', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundid', models.CharField(max_length=250)),
                ('outdate', models.CharField(max_length=200)),
                ('indate', models.CharField(max_length=200)),
            ],
        ),
    ]
