# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250)),
                ('ifsc', models.CharField(max_length=250)),
                ('branchname', models.CharField(max_length=250)),
                ('acholdername', models.CharField(max_length=250)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MessFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 11, 2, 11, 39, 19, 923248))),
                ('feedback', models.CharField(max_length=200)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_date', models.DateField(default=None)),
                ('from_date', models.DateField(default=None)),
                ('mail_proof', models.FileField(default=None, upload_to=b'')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student')),
            ],
        ),
    ]
