# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250)),
                ('ifsc', models.CharField(max_length=250)),
                ('branchname', models.CharField(max_length=250)),
                ('acholdername', models.CharField(max_length=250)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MessFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackid', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('feedback', models.CharField(max_length=200)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundid', models.CharField(max_length=250)),
                ('outdate', models.CharField(max_length=200)),
                ('indate', models.CharField(max_length=200)),
                ('mail_proof', models.FileField(default=None, upload_to=b'')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student')),
            ],
        ),
    ]
