# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messfeedback',
            name='feedbackid',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='refundid',
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 18, 5, 17, 231270)),
        ),
    ]
