# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_auto_20181025_1917'),
        ('Mess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250)),
                ('ifsc', models.CharField(max_length=250)),
                ('branchname', models.CharField(max_length=250)),
                ('acholdername', models.CharField(max_length=250)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student')),
            ],
        ),
        migrations.AddField(
            model_name='messfeedback',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student'),
        ),
        migrations.AddField(
            model_name='refund',
            name='mail_proof',
            field=models.FileField(default=None, upload_to=b''),
        ),
        migrations.AddField(
            model_name='refund',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel.Student'),
        ),
    ]
