# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 11, 39, 46, 810966)),
        ),
    ]
