# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0002_auto_20181031_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 18, 6, 36, 747429)),
        ),
    ]
