# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0004_auto_20181101_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 14, 4, 6, 633704)),
        ),
    ]
