# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mess', '0010_auto_20181102_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='indate',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='outdate',
        ),
        migrations.AddField(
            model_name='refund',
            name='from_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='refund',
            name='to_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 1, 40, 27, 671138)),
        ),
    ]
