# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(default=0, max_length=15)),
                ('first_name', models.CharField(default=0, max_length=50)),
                ('middle_name', models.CharField(default=0, max_length=50)),
                ('last_name', models.CharField(default=0, max_length=50)),
                ('regis_year', models.IntegerField(default=0)),
                ('gender', models.CharField(default='m', max_length=1)),
            ],
        ),
    ]
