# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_grp',
            field=models.CharField(default='B-', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='curr_sem',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='student',
            name='curr_year',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@iiits.in', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='regis_deg',
            field=models.CharField(default='B.Tech', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='regis_deg_dur',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='regis_year',
            field=models.IntegerField(default='2016'),
        ),
    ]
