# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutlist',
            name='in_time',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='inoutlist',
            name='out_time',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
