# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomregistration',
            name='room_no',
        ),
        migrations.AddField(
            model_name='guestentry',
            name='guest_age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='guest_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='roomregistration',
            name='pref_room_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hostelcomplaint',
            name='complain_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_grp',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='curr_sem',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='curr_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regis_deg',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regis_deg_dur',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='regis_year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
