# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelcomplaint',
            name='complain_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
