# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_auto_20181030_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelcomplaint',
            name='complain_time',
            field=models.DateTimeField(default=None),
        ),
    ]
