# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_auto_20181101_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutlist',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inoutlist',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 23, 49, 46, 397771)),
        ),
        migrations.AlterField(
            model_name='inoutlist',
            name='out_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 23, 49, 46, 397807)),
        ),
    ]
