# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-01 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_auto_20181101_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutlist',
            name='in_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 1, 57, 20, 194628)),
        ),
        migrations.AlterField(
            model_name='inoutlist',
            name='out_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 1, 57, 20, 194674)),
        ),
    ]
