# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_auto_20181030_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomregistration',
            name='fee_proof',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
