# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 18:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0004_auto_20181024_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(default='', max_length=15)),
                ('guest_gender', models.CharField(max_length=1)),
                ('no_of_stay', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HostelComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(default='', max_length=15)),
                ('complaint', models.CharField(default='', max_length=500)),
                ('complain_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='InOutList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(default='', max_length=15)),
                ('in_time', models.DateTimeField(default=datetime.datetime.now)),
                ('out_time', models.DateTimeField(default=datetime.datetime.now)),
                ('out_reason', models.CharField(default='', max_length=500)),
                ('out_place', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(default='', max_length=15)),
                ('room_no', models.IntegerField(default=0)),
                ('fee_proof', models.FileField(upload_to=b'')),
                ('hostel_name', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
